spring:
  profiles: db

  datasource:
    hikari:
      meta:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
        jdbc-url: jdbc:mysql://localhost:3306/meta_db?serverTimezone=UTC
      biz:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
        jdbc-url: jdbc:mysql://localhost:3307/biz_db?serverTimezone=UTC
