spring:
  profiles:
    active: local


---

spring.profiles: local

spring:
  application:
    name: batch-mail-service

  profiles:
    include: db

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect